from sleep2vec2.metrics.ahi import (
    AHI_COARSE_THRESHOLD_GRID,
    AHI_FINE_THRESHOLD_GRID,
    AHI_MIN_EVENT_DURATION,
    AHI_MIN_TST_HOURS,
    AHI_SEGMENT_MERGE_TOLERANCE,
    AHI_SEVERITY_THRESHOLDS,
    AHI_THRESHOLD_GRID,
    PreparedAHIRecord,
    compute_ahi_event_metrics,
    compute_ahi_pointwise_metrics,
    extract_ahi_summary_scatter_arrays,
    filter_segments_by_stage,
    merge_intervals,
    select_best_ahi_threshold,
)
from sleep2vec2.metrics.core import (
    binary_positive_scores_from_two_logits,
    binary_sequence_to_segments,
    binary_specificity,
    compute_binary_label_metrics,
    compute_binary_probability_metrics,
    compute_downstream_metrics,
    compute_multilabel_classification_metrics,
    compute_multilabel_metrics_by_disease,
    compute_survival_c_index,
    compute_survival_c_index_by_disease,
    filter_segments_by_duration as _filter_segments_by_duration,
    icc2_two_raters_arrays,
    macro_specificity,
    roc_auc_from_two_logits,
    vectorized_event_stats,
)

__all__ = [
    "AHI_COARSE_THRESHOLD_GRID",
    "AHI_FINE_THRESHOLD_GRID",
    "AHI_MIN_EVENT_DURATION",
    "AHI_MIN_TST_HOURS",
    "AHI_SEGMENT_MERGE_TOLERANCE",
    "AHI_SEVERITY_THRESHOLDS",
    "AHI_THRESHOLD_GRID",
    "PreparedAHIRecord",
    "binary_positive_scores_from_two_logits",
    "binary_sequence_to_segments",
    "binary_specificity",
    "compute_ahi_event_metrics",
    "compute_ahi_pointwise_metrics",
    "compute_binary_label_metrics",
    "compute_binary_probability_metrics",
    "compute_downstream_metrics",
    "compute_multilabel_classification_metrics",
    "compute_multilabel_metrics_by_disease",
    "compute_survival_c_index",
    "compute_survival_c_index_by_disease",
    "extract_ahi_summary_scatter_arrays",
    "filter_segments_by_duration",
    "filter_segments_by_stage",
    "icc2_two_raters_arrays",
    "macro_specificity",
    "merge_intervals",
    "roc_auc_from_two_logits",
    "select_best_ahi_threshold",
    "vectorized_event_stats",
]


def filter_segments_by_duration(intervals, *, min_duration: int = AHI_MIN_EVENT_DURATION) -> list[list[int]]:
    return _filter_segments_by_duration(intervals, min_duration=min_duration)
