from __future__ import annotations

from collections import Counter
import csv
import math
from pathlib import Path
import re
import typing as t


def _sanitize_key_part(value: t.Any) -> str:
    text = re.sub(r"[^A-Za-z0-9_.-]+", "_", str(value)).strip("_")
    return text or "unknown"


def build_embedding_sample_key(*, source_value: t.Any, record_key: t.Any, token_start: int, token_end: int) -> str:
    return f"{_sanitize_key_part(source_value)}_{_sanitize_key_part(record_key)}_{token_start:06d}_{token_end:06d}"


def validate_whole_night_index(
    index_paths: t.Iterable[str | Path],
    *,
    eval_split: str,
    max_source_tokens: int,
    path_base: Path | None = None,
    sources: t.Iterable[str] = (),
) -> dict[str, int]:
    expected_tokens_by_path: dict[str, int] = {}
    sample_keys: set[str] = set()
    selected_sources = tuple(sources)
    for index_path in index_paths:
        index_file = Path(index_path)
        if not index_file.is_absolute() and path_base is not None:
            index_file = path_base / index_file
        with index_file.open(newline="") as csv_file:
            reader = csv.DictReader(csv_file)
            fieldnames = reader.fieldnames or []
            duplicates = sorted(name for name, count in Counter(fieldnames).items() if count > 1)
            if duplicates:
                raise ValueError(f"Whole-night index {index_path} has duplicate columns: {duplicates}")
            required = {"path", "split", "duration"}
            missing = sorted(required - set(fieldnames))
            if missing:
                raise ValueError(f"Whole-night index {index_path} is missing required columns: {missing}")
            for row in reader:
                if None in row:
                    raise ValueError(f"Whole-night index {index_path} contains unexpected extra values.")
                if row["split"] != eval_split:
                    continue
                path = str(row["path"])
                source = row.get("source") or str(index_path)
                if selected_sources and not any(name in str(source) for name in selected_sources):
                    raise ValueError(
                        f"Whole-night path {path} source {source!r} does not match configured sources: "
                        f"{list(selected_sources)}"
                    )
                if path in expected_tokens_by_path:
                    raise ValueError(f"Duplicate whole-night path in selected split: {path}")
                try:
                    duration = float(row["duration"])
                except (TypeError, ValueError) as exc:
                    raise ValueError(f"Invalid duration for whole-night path {path}: {row['duration']!r}") from exc
                if not math.isfinite(duration):
                    raise ValueError(f"Non-finite duration for whole-night path {path}: {duration}")
                duration_tokens = duration / 30
                if not duration_tokens.is_integer():
                    raise ValueError(
                        f"Whole-night path {path} duration must be aligned to 30-second tokens: {duration}."
                    )
                num_tokens = int(duration_tokens)
                if num_tokens < 1 or num_tokens > max_source_tokens:
                    raise ValueError(
                        f"Whole-night path {path} has {num_tokens} source tokens; "
                        f"expected [1, {max_source_tokens}]."
                    )
                record_key = row.get("record_key")
                if not record_key or record_key.strip().lower() in {"", "nan"}:
                    record_key = row.get("session_id")
                if not record_key or record_key.strip().lower() in {"", "nan"}:
                    sample = Path(path)
                    record_key = f"{sample.parent.name}_{sample.stem}"
                sample_key = build_embedding_sample_key(
                    source_value=source,
                    record_key=record_key,
                    token_start=0,
                    token_end=num_tokens,
                )
                if sample_key in sample_keys:
                    raise ValueError(f"Duplicate embedding sample_key generated by whole-night index: {sample_key}")
                sample_keys.add(sample_key)
                sample_path = Path(path)
                if not sample_path.is_absolute() and path_base is not None:
                    sample_path = path_base / sample_path
                if not sample_path.is_file():
                    raise FileNotFoundError(f"Whole-night NPZ path not found: {path}")
                expected_tokens_by_path[path] = num_tokens

    if not expected_tokens_by_path:
        raise ValueError(f"No whole-night rows found for split {eval_split!r}.")
    return expected_tokens_by_path
